### ISSUE TITLE
Add filter for select parent class in create class dialog

### ISSUE THREAD

**Issue by jashcroft123** [opengds/OpenGDS#102]
Match the functionality of the interface portion and add a search/filter field when selecting the parent class
![image](https://github.com/opengds/OpenGDS/assets/54602676/c2cbb536-6a1f-4233-845b-f3d8289331cc)

**Comment by MikaelHolmstrom** [comment]
Why not, I'll add that

**Comment by MikaelHolmstrom** [comment]
![image](https://github.com/opengds/OpenGDS/assets/6456318/f355b982-f451-4667-9a8e-3c887b1504d7)
Added, just need to wait for the next build :-)

**Comment by jashcroft123** [comment]
Great, thanks! Can't wait for this next build :)
