### ISSUE TITLE
Able to create Property Method without selecting a Property

### ISSUE THREAD

**Issue by StefanCals** [opengds/OpenGDS#105]
In the Create Method Dialog, when selecting the Property Method (Method Type), the _Create Method_ and _Create and Open Method_ buttons start of disabled.

![image](https://github.com/opengds/OpenGDS/assets/36990897/af48f33c-16d9-45c0-8624-49d4926fc4e4)

If I put in a Property Name, without selecting a Property first, these buttons will be enabled.

![image](https://github.com/opengds/OpenGDS/assets/36990897/14ffc318-7f06-4ff4-b1bd-d26c178c8fe1)

Clicking on either one of the buttons now results in nothing (because I didn't select a property obviously).

But then you shouldn't be able to click on the Create buttons. So possibly add an extra check if a property was actually selected before enabled the buttons.

**Comment by MikaelHolmstrom** [comment]
Fixed
