### ISSUE TITLE
Cannot use Icon editor or rename vi when class is not in project

### ISSUE THREAD

**Issue by Bas-vE** [opengds/OpenGDS#106]
When I have a class opened in the project view (so not loaded inside a project) opening the icon editor or renaming a method results in an error

![image](https://github.com/opengds/OpenGDS/assets/16207111/d1bd2586-c88e-4291-9724-8e52468b8d80)

This error when the rename is called

![image](https://github.com/opengds/OpenGDS/assets/16207111/cf310eac-2aff-46f1-a2d1-3c8821ad62ae)

This error when the icon editor is opened
![image](https://github.com/opengds/OpenGDS/assets/16207111/dc96522f-f2d7-46df-86b0-0231913686bc)

**Comment by MikaelHolmstrom** [comment]
Fixed
