### ISSUE TITLE
Vim icon editor

### ISSUE THREAD

**Issue by jashcroft123** [opengds/OpenGDS#107]
Would it be possible for the tool to detect if the current vi is a .vim the colour should default to that orangy yellow of vim's recommended by ni

**Comment by Bas-vE** [comment]
You mean the color that NI is using for it's own vims? 
![image](https://github.com/user-attachments/assets/1affebc7-9659-407e-887d-4807669eb39d)

Is this color something NI recomments using for vims? I cannot seem to find an article where they say so.

I don't think I would like my vims in a specific class to default to that color. I still want them to have the same color scheme as the rest of my class methods. Maybe when you're changing the icon of a vim thats outside of a library or class you would want to default to a specific color. But I don't think we should force vim's to always default to that orange NI color.

**Comment by jashcroft123** [comment]
That's the colour (255,204,153). I thought I read it in NI documentation, it is in fact an article by DMC. That's a fair opinion, I tend to use the colour but retain the class header.

**Comment by Bas-vE** [comment]
For now we will not implement this, maybe if NI wants standarized colors for specific vi types we can revisit this issue
