### ISSUE TITLE
Derived Class has Interface Box

### ISSUE THREAD

**Issue by pettaa123** [opengds/OpenGDS#111]
I just installed GOOP from vipm on a fresh LabVIEW installation. When using-> GOOP Create Derived Class -> Wire Editor -> Random Button -> OK , the derived class carries a interface style box in the project viewer.
![image](https://github.com/user-attachments/assets/d46f5d5d-3185-45ae-8f14-02bb3a301167)

**Comment by Bas-vE** [comment]
I can reproduce this

**Comment by MikaelHolmstrom** [comment]
Same here :-), better check what's going on :-)

**Comment by MikaelHolmstrom** [comment]
Fixed
