### ISSUE TITLE
Clone VI Dialog cannot handle class names containing "."

### ISSUE THREAD

**Issue by Flydroid** [opengds/OpenGDS#117]
I use dots - "."  to namespace my child classes. 
The Clone VI dialog doesn't seem to be able to update the path based on the selected class if that class contains a "." in the name. 
The path then defaults to the parent class folder. 

![image](https://github.com/user-attachments/assets/d5311420-80a5-412b-af06-2f6bf118fab0)

The expected folder path would be C:\Git\ExperimentController\ExperimentController_Source\Subsystems\Subsystem.DAQmx\Finish.vi

Manually selecting the path also doesn't work, only if I write the path the vi lands in the correct folder. 
I wanted to do debug deeper and possibly figure out the fix but the "DialogCloneMethod.vi" in ClassWriterNative_Class doesn't seem to be the VI which gets called, as any breakpoints in the vi don't stop the execution.

**Comment by MikaelHolmstrom** [comment]
Done
