### ISSUE TITLE
Connector Pane Class Tool should not operate on property VIs

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#13]
LabVIEW has a limitation, in that VIs used for RW property nodes must have a 4x2x2x4 connector pane pattern. So if you apply a new connector pane pattern with the tool that is different than this configuration, you will break all your property VIs.

My suggestion would be to put a note on the UI informing the user that regardless of what they pick, the property VI connector panes are ignored. Also make sure to ignore these VIs.

**Comment by MikaelHolmstrom** [comment]
Fixed
