### ISSUE TITLE
Create Method dialog cannot create private properties in public properties folder.

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#14]
When using the create method dialog, there is an issue when creating private properties.
If the properties folder is set to public, then if you try to create a private property using this dialog, it doesn't get created as private. I think the properties folder is set to public if you create a public property with this dialog? Not sure.

If I change the property folder access scope to "Not Specified" then it works fine. Private properties can be created with the dialog. I suggest that the properties folder be set to "Not Specified" always.

**Comment by MikaelHolmstrom** [comment]
You are right the tool creates the "properties" folder with Public access scope, I'll change it to "Not Specified"
