### ISSUE TITLE
Method Signature Dialog shows the <Symbio> logo

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#15]
![screen shot 2016-09-26 at 10 36 32 pm](https://cloud.githubusercontent.com/assets/7982554/18861405/d3481920-8439-11e6-9ee7-7ef459efe83d.png)

Method Signature Dialog shows the <Symbio> logo.
BTW, what the heck is this dialog for?

**Comment by MikaelHolmstrom** [comment]
Good catch, this was a request to add a common VI Description to all our methods.
I'm not using this feature, and I'm not sure whoever does, but it came from a customer a long time ago.
I'll fix it anyway.
