### ISSUE TITLE
GDS 1.2.8 produces an error when attempting to edit an Icon VI when the class is in a Real-time target

### ISSUE THREAD

**Issue by tyk007007** [opengds/OpenGDS#17]
Had this issue when attempting to modify a class method icon when the class is located in a real-time target. After selecting the right-click option the crash popup appears immediately.

Moving the class temporarily to the My Computer target allowed the edit popup and functionality to work correctly. See screenshot and content below:

![goop_error](https://cloud.githubusercontent.com/assets/7832389/20406525/8c6a9dae-ad72-11e6-81b8-b3a0ec7c1baf.png)

[goop_error_log.txt](https://github.com/opengds/OpenGDS/files/598406/goop_error_log.txt)

**Comment by MikaelHolmstrom** [comment]
Good catch, I'll fix that in the next release.
There is a workaround though.
Open the VI, then use the "Tools->GOOP->Create VI Icon..." option from the VI's menu.
Then it works

**Comment by tyk007007** [comment]
Ah great, I'll use the workaround for now.

**Comment by MichaelAivaliotis** [comment]
Just verified that this issue is fixed.
