### ISSUE TITLE
error message when trying to edit icon of VI in RT application instance.

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#21]
If I right-click on a VI which is shown as a dependency in the RT application instance. OpenGDS pops up an error message stating the VI is not in memory. I assume this is happening because OpenGDS operates in the My Computer application instance and cannot cross boundaries. This is an acceptable limitation for me. However, the message should be more friendly and not so scary. Or the right-click menu should be disabled for unusable functions in the RT application instance (which is preferable). Or maybe allow it and popup an explanation.
![screen shot 2017-03-21 at 3 40 21 pm](https://cloud.githubusercontent.com/assets/7982554/24174212/becbcb02-0e4c-11e7-8cea-38d48b42494c.png)

**Comment by MichaelAivaliotis** [comment]
Just noticed that it's fixed in latest commit.

**Comment by MikaelHolmstrom** [comment]
That's good :-)
I've done some updates on the Class Tool, and will soon have a more to show there :-)
