### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by marcelvanthoff** [opengds/OpenGDS#24]
I'm seriously missing documentation for the OpenGDS project. 

The help windows luckily give some information, but I could not find any documentation explaining concepts or how to use the software. It's more trial-and-error for discovering how things work, than reading what concepts are and how to use them.

**Comment by MikaelHolmstrom** [comment]
Under Help->GOOP Help… you’ll find some basic help.
(or you can just open the help html file: file:///C|/Program%20Files/National%20Instruments/LabVIEW%202016/resource/Framework/Providers/Open_GDS/HelpFiles/OpenGDS_GOOPHelp.htm)
You can view the videos as well:
http://www.youtube.com/watch?v=UcUj_Gl1JdI
https://www.youtube.com/watch?v=hdcHYS_ZFr8
http://www.youtube.com/watch?v=_BvIiU2VMAU
http://www.youtube.com/watch?v=ZWeO_wPe-VQ
http://www.youtube.com/watch?v=OunqB9UdR6o
http://www.youtube.com/watch?v=VncaD_pKe_s
http://www.youtube.com/watch?v=i77lHDIMs_s
I do have some more videos I like to post:
1) Describing the Conversion tool of Java/C# code to LabVIEW.
     Tools->GOOP/Conversion->Convert Text based code to LabVIEW
2) The New Class Tool…
Cheers,
Mike
