### ISSUE TITLE
Change how object properties are named

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#27]
I love using object properties and openGDS makes an easy job of it. However, the default property node naming convention does not fit with my style. It would be nice to let the property names (upper\lower case with space) match the object data control names instead of your truncated CamelCase implementation.

Or have the option to toggle between these two options in the creator dialog?

**Comment by MikaelHolmstrom** [comment]
Sure, easy fix.
If you don't care about that the VI will use camel case, you can change the Property Name manually just by adding the spaces back in to the **Property Name** before you press **Create Method**
![createpropertynodemethod](https://cloud.githubusercontent.com/assets/6456318/25785535/9119a19e-33c6-11e7-8c21-fda373666dfd.png)

**Comment by MichaelAivaliotis** [comment]
Yes I noticed I could do that. However, it's tedious to do every time. Most of the time I click on a few options and click create. I don't bother with details and don't have time to edit. Also, if you select multiple attributes, that text field becomes long and difficult to edit.

So does this mean you will add a checkbox or something?

**Comment by MikaelHolmstrom** [comment]
fixed in 1.2.19
