### ISSUE TITLE
Selecting multiple VIs for cloning

### ISSUE THREAD

**Issue by marcelvanthoff** [opengds/OpenGDS#28]
I really like the feature to clone a class or just a single VI in the project explorer. 

Would it be possible to select multiple VIs or a property definition folder or a virtual folder to clone all selected/containing VIs?

**Comment by MikaelHolmstrom** [comment]
I've added support for multiple VI selection and cloning, but for some reason the project provider framework don't always trigger this correctly.
![image](https://user-images.githubusercontent.com/6456318/27157898-5663bb44-51a7-11e7-9116-16ea2ef7ce1d.png)
I don't support cloning of virtual folders yet, and VIs in the property definition folder might not work either.
