### ISSUE TITLE
Improvement: Modify this class inheritance dialog, change selector to combobox

### ISSUE THREAD

**Issue by kosist** [opengds/OpenGDS#31]
"Modify this class inheritance" dialog has list of classes, from which current class could be inherited. It'd be nice, if one could type there class name (like combobox), so target class could be found immediately. Now one has to scroll over all the classes names + they are not sorted in alphabetical order.

**Comment by BenvanSeggelen** [comment]
I implemented a combo box like you suggested. If Mike approves the issue should be solved.
