### ISSUE TITLE
When there is no data in the class object, then creating any method gives an error

### ISSUE THREAD

**Issue by digiajay** [opengds/OpenGDS#34]
I usually work around this with the dummy data in my Native LVClass.  Else, I would get an error and broken BD as below.

![screenshot 21-01-2018 074726](https://user-images.githubusercontent.com/6551395/35190091-923a2844-fe7f-11e7-804e-67d930ef3190.png)

![screenshot 21-01-2018 074933](https://user-images.githubusercontent.com/6551395/35190098-a70b6c1a-fe7f-11e7-9059-b23a683a192b.png)

**Comment by MikaelHolmstrom** [comment]
Thanks for pointing this out.
I've fixed the issue and it will be added into the next build 1.2.25

**Comment by digiajay** [comment]
Cool.!
