### ISSUE TITLE
Broken Actor Framework Class Provider 

### ISSUE THREAD

**Issue by patricjenni** [opengds/OpenGDS#41]
When creating a new method for an actor (right click 'My Actor.lvclass' -> GOOP -> Add Method and the check box 'Create Actor Framework Message class for this actor method' set) the resulting send method (Send Foo.vi) will be broken.

I tracked down the issue and it looks like the VI <LabVIEW Install Dir>\resource\Framework\Providers\Open_GDS\ClassProviders\ActorFramework\4.0.0\Message\Send Template.vi is broken. Unchecking the 'Allow debugging' solves the problem.

I'm using LabVIEW 2016 (16.0f5) and GOOP 1.2.31 with the shipped version 4.1.0 of the actor framework.

**Comment by MikaelHolmstrom** [comment]
Thanks for finding it. The issue is that the VI is configured as Inline SubVI and Allow debugging.
I'll make sure the next build don't set the inline subVI check box.
