### ISSUE TITLE
Creating a override VI does not reuse the icon of the parent VI

### ISSUE THREAD

**Issue by patricjenni** [opengds/OpenGDS#42]
When creating a class (eg. Child.lvclass) which inherits from a parent class containing a dynamic dispatch VI (eg. Parent.lvclass:foo.vi), the icon of the child method does not reuse the icon of the parent method.

- Icon of 'Parent.lvclass:foo.vi'
![parent - foo icon](https://user-images.githubusercontent.com/36151432/45754306-984b2300-bc1b-11e8-8e6b-778a0c3674b9.PNG)

- Icon of 'Child.lvclass:foo.vi'
![child - foo icon](https://user-images.githubusercontent.com/36151432/45754303-984b2300-bc1b-11e8-8149-55de46ce7333.PNG)

NI's implementation does reuse the icon of the parent method. I'd expect GOOP's implementation to be similar.

**Comment by MikaelHolmstrom** [comment]
Hmm, sure why not.
I'll add that as the default option, but with the child class's defined background color.

**Comment by MikaelHolmstrom** [comment]
Fixed in latest Source code, will build a new version very soon 1.2.38
