### ISSUE TITLE
Tabbing order in dialog windows

### ISSUE THREAD

**Issue by kosist** [opengds/OpenGDS#44]
It would be handy to fix tabbing order for clone class window (maybe for others also, it is possible to check remaining then). Now it is tabbing even though invisible controls, but I guess that main buttons should be tabbed first.
Current:
![current](https://user-images.githubusercontent.com/1911151/47356003-2f941200-d6c3-11e8-8a9e-cd536bdaa498.png)
Preferable:
![preferrable](https://user-images.githubusercontent.com/1911151/47356011-36228980-d6c3-11e8-847f-8b36b707d6ea.png)

**Comment by MikaelHolmstrom** [comment]
Added in 1.2.39
