### ISSUE TITLE
Updating icon using GOOP deletes the VI description

### ISSUE THREAD

**Issue by digiajay** [opengds/OpenGDS#45]
When I update the method icon using *project->class->method->right click->GOOP->Edit icon*, the descriptions saved earlier in the method gets removed.

**Comment by MikaelHolmstrom** [comment]
Hmm I can't reproduce this, what are the steps?
BTW Thanks for all feedback

**Comment by digiajay** [comment]
Hi @MikaelHolmstrom 

I couldn't get for long..  Here are the reproduction steps.

1. In LV project explorer, create a class and create a method in it.
2. Open that method VI and go to VI Properties --> Documentation, then add some documentation and save that VI and close.
3. Go to project explorer, right click that method and update edit the icon using GOOP.
4. Go to VI properties and find that it's documentation is missing.
