### ISSUE TITLE
UML opening in LabVIEW 2015

### ISSUE THREAD

**Issue by alexgieg** [opengds/OpenGDS#5]
I get this error when double-clicking a UML file in the Project Explorer in LabVIEW 2015:

![opengds bug 1](https://cloud.githubusercontent.com/assets/1074619/9182170/a9ced19c-3f7f-11e5-8b2f-408976cb657c.png)

Followed by this:

![opengds bug 2](https://cloud.githubusercontent.com/assets/1074619/9182193/ce7b4e12-3f7f-11e5-9b97-46d5e8017a60.png)

Opening the UML file in the Open UML Modeller directly works normally.

**Comment by unifab** [comment]
We had a similar issue with our toolkit and it turned out that VIPM was not mass compiling the VIs when installing on LabVIEW 2015. 

I wonder if this is the same issue.

**Comment by MikaelHolmstrom** [comment]
I'll work on it.

**Comment by MikaelHolmstrom** [comment]
Download the untested versinon 1.1.12 http://opengds.github.io/
I just re-build the 2015 UML Open-er application that is linked to the uml-extension.

**Comment by alexgieg** [comment]
I've tried the new 1.1.12 version. Unfortunately the issue remains, with the exact same error dialogs.

**Comment by alexgieg** [comment]
PS.: I've also checked the registry to make sure the system is calling "UmlMessager_2015.exe", not other version, and it is.

**Comment by MikaelHolmstrom** [comment]
Good new, I get the same problem as well on my work computer.
I should be able to figure it out now :-)

**Comment by MikaelHolmstrom** [comment]
I've rebuilt the UmlMessager_2015.exe now.
Download it manaully and replace it.
https://github.com/opengds/OpenGDS/blob/master/resource/Framework/Providers/Open_GDS/UmlMessage/UmlMessager_2015.exe

**Comment by alexgieg** [comment]
Awesome! It's working flawlessly now. Thank you very much!
