### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by BenvanSeggelen** [opengds/OpenGDS#50]
There are 2 unnecessary files in the DesignPatterns/ActiveObjects folder that can be removed.

Files:
1. ../Open_GDS/ClassProviders/DesignPatterns/ActiveObjects/ActiveObjects_DynamicEvents_SubVIs_VIT.aliases
2. ../Open_GDS/ClassProviders/DesignPatterns/ActiveObjects/ActiveObjects_DynamicEvents_SubVIs_VIT.lvlps

I placed them there when I was testing my own ActiveObject template

**Comment by MikaelHolmstrom** [comment]
Hmm, I don't see those in the repo

**Comment by Bas-vE** [comment]
This should be fixed in the next release, I've removed them from the master branch
