### ISSUE TITLE
Rename VI is changing file extension of controls to .vi

### ISSUE THREAD

**Issue by tgutzler** [opengds/OpenGDS#51]
When I'm using the "GOOP/Rename VI..." context menu option to rename a vi in an EndevoGOOP400 class and change the text in "New Name", the extension gets changed from .ctl to .vi. You can see the result in the screenshot below

![image](https://user-images.githubusercontent.com/14195272/64754045-d34f1080-d568-11e9-84aa-4b075f461fc5.png)

**Comment by MikaelHolmstrom** [comment]
Fixed, in my DQMH branch
