### ISSUE TITLE
Error Handling in Active Object Template

### ISSUE THREAD

**Issue by Bas-vE** [opengds/OpenGDS#54]
In the GOOP4 Active Object template an error wil stop the whole process, and there is no way to know this happened, especially in bigger projects. So we were wondering why the error is handled in this way, is this by design? And is it possible to change this? like not stop te process but report the error, or maybe make it an option in the StartProcess.vi to exit on error or not. Especially for programmers that are new to reference based objects in LabVIEW this is not something they are familiar with.

I just want to know your opinion on this. and maybe you have a different approach to this problem.

**Comment by MikaelHolmstrom** [comment]
You are right, there are some important things missing in the process VI. That's why we have created our own active object design pattern.
That design is using lots of OpenG VIs and is based on JKI's queued state machine.
Feel free to modify it the way you think it should look like and I can push that in for the next release.

**Comment by MikaelHolmstrom** [comment]
@Bas-vE , have you figured made a better template you like me to update to?
I can add the design I use at work, but it requires some extra VIs/packages installed

**Comment by Bas-vE** [comment]
We also have a design which is based or inspired by the JKI statemachine, I'm now discussing at vi-tech if this is something we need to modify to be available publicly. You don't mind having dependencies to other packages?

I personally love how OpenGDS doesn't have any dependencies to other packages, which makes it easy to share code without having the other person to have the tool. If we are doing something inspired by the JKI statemachine, we have to add 2 additional vi's to the class.

Is it possible to see the design you have?

**Comment by MikaelHolmstrom** [comment]
Here is a screen shot of some of the features we have in our version.
![image](https://user-images.githubusercontent.com/6456318/152237922-9791e93b-8544-4003-90fb-def58671d8c7.png)

**Comment by Bas-vE** [comment]
So our template is a bit different, and we would like to share it with you. Right now it has a dependency to the JKI Statemachine, which i'm not a fan of when using the OpenGDS. We are very interested in your StringBase state parsing VI. Our question is, is this vi part of the class, project or part of the plugin? if the vi is part of the class or project, we would like to see if we can use that in our template as well and share that with you.

This is our template and as you can see it still used the JKI state vi's. we can modify this and add these to a utils folder of the project or to the utils folder of each class, the downside to adding this to each class is code duplication. Our goal is that these parser methods are part of the project so you won't have any dependencies. I hope you can agree with me on this one.
![image](https://user-images.githubusercontent.com/16207111/152319339-ab7d1893-dca9-4560-81e5-c80cadd08af5.png)

**Comment by MikaelHolmstrom** [comment]
Either we add these extra VIs in the utils folder of the class, or in the common <addons>\_goop4.llb
But if you share this code with someone, they need that llb.
Your code looks clean, I prefer to prefix the command coming in, if you don't someone can send your state machine to an illegal/private state, just by using that command name :-).
Can you send your your code, so I can have a detailed look in it?
mikael@holmstroms.eu

**Comment by MikaelHolmstrom** [comment]
Sorry, I can't find the code, can you send it to me again?

**Comment by Bas-vE** [comment]
I think this issue can be closed because the new template is in the >2020 version of the GDS
