### ISSUE TITLE
Edit Class Icon error with an Interface

### ISSUE THREAD

**Issue by vekkuli** [opengds/OpenGDS#56]
Selecting "Edit Class Icon..." on an Interface produces OpenGDS Error dialog with the following Error String:

```
Error 1709 occurred at Property Node (arg 1) in GDSLvClass_GetRootBaseClass.vi->GDSLvIcon_DialogUpdateClass.vi->GOOP_LVClass_Item_OnCommand.vi->GOOP_LVClass_Item_OnCommand.vi.ProxyCaller

Possible reason(s):

LabVIEW: (Hex 0x6AD) Interfaces do not have parent classes. Interfaces can only inherit from other interfaces.Property Node (arg 1) in GDSLvClass_GetRootBaseClass.vi->GDSLvIcon_DialogUpdateClass.vi->GOOP_LVClass_Item_OnCommand.vi->GOOP_LVClass_Item_OnCommand.vi.ProxyCaller
```

**Comment by MikaelHolmstrom** [comment]
Thanks.
There are several things that's not working for interfaces.
We're working on a dedicated LV2020 release that will have support for the native interface classes

**Comment by vekkuli** [comment]
That's great to hear. I imagined it might be just that. Hopefully you don't mind me opening the issue to track the completion.

**Comment by MikaelHolmstrom** [comment]
Sorry, forgot to close this one.
There is a new build coming in the next 24 hours
