### ISSUE TITLE
Error 0x692 in UMLModeller on LV2019.0.f2

### ISSUE THREAD

**Issue by N-Powl** [opengds/OpenGDS#57]
The constant for the UMLModeller Main Open case for Pattern (All Files) causes error 0x692 due to the use of \00 in the constant, as this is a null constant. Reproduced the Open File Dialog with that constant in a small VI and see the same behaviour:

![image](https://user-images.githubusercontent.com/73291436/96870549-fa188f80-1468-11eb-85f4-7c010b344484.png)

Workaround to replace the null characters with a semicolon as divisor, but this should probably be changed from the original installer.

**Comment by MikaelHolmstrom** [comment]
Fix in the later versions
