### ISSUE TITLE
Race condition in dynamic events active object process

### ISSUE THREAD

**Issue by JeffreyHabets** [opengds/OpenGDS#6]
See the image (attached) of the active object’s process. Because the ‘process starter’ is notified that the process is started before the process registered for events, it is possible that events get sent before the register for events node is executed -> race-condition.
To fix this, I think it’s best to move the ‘Started’ notification inside the Init-case and call it after the register for events node has executed.
 
![ao_process race condition](https://cloud.githubusercontent.com/assets/7666895/10831629/12aac252-7e87-11e5-9e1e-9c9510e5a10a.png)

**Comment by MikaelHolmstrom** [comment]
Thanks, I'm uploading 1.1.15 that have this fixed
