### ISSUE TITLE
LabVIEW Native Interface not supported

### ISSUE THREAD

**Issue by Pacome21** [opengds/OpenGDS#62]
Hi,

It would be a go idea to integrate the new native interface of LabVIEW.

This interface is available since LabVIEW 2020.

Regards.

**Comment by MikaelHolmstrom** [comment]
Done :-)
Check out the beta version, we've been using that at work for the last 3 month.
http://opengds.github.io/

**Comment by Pacome21** [comment]
Hi Mikael,

 

Thanks for the answer.

 

Is it possible to subscribe to a mailing list to be notified when a new
version is available?

 

Have a nice day.

 

Christophe Scherly

**Comment by MikaelHolmstrom** [comment]
Subscribe to this:
https://forums.ni.com/t5/GDS-Goop-Development-Suite/bd-p/5050?profile.language=en

**Comment by MikaelHolmstrom** [comment]
New 2020 version ready
