### ISSUE TITLE
labview 2020 64 bit

### ISSUE THREAD

**Issue by 158545614** [opengds/OpenGDS#63]
create read/write method VI name is not correct

![1](https://user-images.githubusercontent.com/65331444/113876697-8dad0500-97ea-11eb-95f8-cd4a3881078d.png)

**Comment by MikaelHolmstrom** [comment]
Is that using the latest Beta Build (v1.2.54)?
I haven't been able to reproduce it yet.

**Comment by MikaelHolmstrom** [comment]
I found another bug and I've added .vim creation support.
But I can't replicate this error :-(.
Can you send my the class example?

**Comment by 158545614** [comment]
[Desktop.zip](https://github.com/opengds/OpenGDS/files/6275248/Desktop.zip)
![R~N_S(TYCPE2SV3A2S}O9XH](https://user-images.githubusercontent.com/65331444/113952373-258d0c00-9848-11eb-8cee-960cea79f8c2.png)
this pitcure show the other bug?

![1](https://user-images.githubusercontent.com/65331444/113952428-39d10900-9848-11eb-9624-47de2f62df34.png)
what is the differences about these two method？

**Comment by MikaelHolmstrom** [comment]
Interesting...

**Comment by 158545614** [comment]
> Interesting...

Do you reproduce these bugs？

**Comment by 158545614** [comment]
> Interesting...

Hi Do you replicate these errors??

**Comment by MikaelHolmstrom** [comment]
I've not found the issue yet.
You can always help he out and probe some values in the VI:
C:\Program Files (x86)\National Instruments\LabVIEW 2020\resource\Framework\Providers\Open_GDS\ClassProviders\Provider_LvNativeClass\ClassWriterNative_class\DialogCreateMethod.vi
...to see what's going on.
To debug this VI (or any OpenGDS VIs), open the VI, enable "Allow debugging" (VI Properties/Execution), add a Break Point on the BD in the VI and save it.
Then restart LV and when this VI gets called the BD will open and you can debug it.
After the VI gets closed, the debugging stops working so to debug it again, you have to restart LV and repeat the process.

**Comment by MikaelHolmstrom** [comment]
BTW regarding the Property Method:Get/Set or Property Node:Read/Write, if you use the Property Node:Read/Write, you can read and write object attribute values using a standard Property Node VI (QD: rn).
You could of course use thee Read/Write VI as normal SubVIs but that's not their intention.

**Comment by 158545614** [comment]
> BTW regarding the Property Method:Get/Set or Property Node:Read/Write, if you use the Property Node:Read/Write, you can read and write object attribute values using a standard Property Node VI (QD: rn).
> You could of course use thee Read/Write VI as normal SubVIs but that's not their intention.



> I've not found the issue yet.
> You can always help he out and probe some values in the VI:
> C:\Program Files (x86)\National Instruments\LabVIEW 2020\resource\Framework\Providers\Open_GDS\ClassProviders\Provider_LvNativeClass\ClassWriterNative_class\DialogCreateMethod.vi
> ...to see what's going on.
> To debug this VI (or any OpenGDS VIs), open the VI, enable "Allow debugging" (VI Properties/Execution), add a Break Point on the BD in the VI and save it.
> Then restart LV and when this VI gets called the BD will open and you can debug it.
> After the VI gets closed, the debugging stops working so to debug it again, you have to restart LV and repeat the process.

![WJ$@@PR~_ZFARH }K5$JENE](https://user-images.githubusercontent.com/65331444/114384611-8490af00-9bc1-11eb-8045-2eff504c0d53.png)

Did you open this project? is it correct??

**Comment by MikaelHolmstrom** [comment]
There is no issue with the project when I use it?!?!?
![image](https://user-images.githubusercontent.com/6456318/114461734-74122000-9c25-11eb-8af1-af4e7c25c434.png)

**Comment by 158545614** [comment]
> There is no issue with the project when I use it?!?!?


![W4NF_0JG696TN6VC@{( A9C](https://user-images.githubusercontent.com/65331444/114648437-5b7f3400-9d11-11eb-9969-71bb98e1d93b.png)

I find this _property ctl seems not correct. what is the problem?

**Comment by 158545614** [comment]
> There is no issue with the project when I use it?!?!?
> ![image](https://user-images.githubusercontent.com/6456318/114461734-74122000-9c25-11eb-8af1-af4e7c25c434.png)


![3R9WW__9$NB5KP1}2Q`NAGS](https://user-images.githubusercontent.com/65331444/114650783-69cf4f00-9d15-11eb-9980-a7828e1472ff.png)

it seems labview'bug??
