### ISSUE TITLE
Dynamic Dispatch checkbox changes state after Property Name edit in Create Method Dialog

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#65]
In LV2020 branch
Ways to reproduce issue:

1. Open Create Method dialog and select to create a property node
2. uncheck the Dynamic Dispatch checkbox
3. Edit the Property Name
4. You will notice that the Dynamic Dispatch checkbox is unchecked.

![Screen Shot 2021-04-23 at 8 06 10 PM](https://user-images.githubusercontent.com/7982554/115945470-d6162500-a470-11eb-9e21-8ee192bb1861.png)

**Comment by MichaelAivaliotis** [comment]
As a secondary request. I believe this checkbox should remember the last state from a previous usage of this dialog. There seems to be no way to configure this.

**Comment by MichaelAivaliotis** [comment]
Is there going to be any movement on this?

**Comment by MikaelHolmstrom** [comment]
Absolutely, thanks for reminding me.

**Comment by MikaelHolmstrom** [comment]
Fixed, I'll just have to build a new release, unless you want to checkout the code and run it from the LV2020 branch

**Comment by MikaelHolmstrom** [comment]
Try the new untested version 1.2.73
