### ISSUE TITLE
Create and Open VI label in Clone VI dialog should be changed to Clone and Open VI to match first button.

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#66]
LV2020 branch
In the Clone VI dialog there is an inconsistency in the button labeling. In the first button the label is: "Clone VI", so it seems proper for the second button to be labeled: "Clone and Open VI".

![Screen Shot 2021-04-23 at 11 04 29 PM](https://user-images.githubusercontent.com/7982554/115949240-82afd100-a488-11eb-8dd6-26a2924e028d.png)

**Comment by MichaelAivaliotis** [comment]
As a secondary note: The tip strips on both buttons are wrong and state: "Create class". The tip strip should either be fixed or removed.

**Comment by MikaelHolmstrom** [comment]
Thanks for that now, I've fixed this and will do another build this week.
Uploaded a new build yesterday with most lots of new UI changes and changes in the Rename VI, to handle interfaces better

**Comment by MikaelHolmstrom** [comment]
BTW, found that the tip strip was wrong in al dialogs, that is also now fixed
