### ISSUE TITLE
Bug in Dynamic Dispatch Property Node Accessor VI Creation

### ISSUE THREAD

**Issue by RaphSchru** [opengds/OpenGDS#68]
Following this issue posted by Darren: https://github.com/opengds/OpenGDS/issues/64
Now the fix broke the creation of dynamic dispatch prop node accessors.

The prop node VIs are unconditionally set to reentrant / preallocated clone + inline.
This is correct for static dispatch, but there should be a distinction to set dyn dispatch prop node VIs to non-reentrant + not inlined:

![image](https://user-images.githubusercontent.com/31904233/117090381-77965400-ad58-11eb-99c0-89dacfe2c80a.png)

I cannot really propose a new implementation since I couldn't figure out why there are 3 possible values for DynamicDispatch (False, True, Mixed), I didn't dig too much into the code.

Using OpenGDS vipm package 1.2.57.120 on LV2020.

**Comment by MikaelHolmstrom** [comment]
Thanks for the feedback, I hope to have a new version for you that fixes this in a few days.

**Comment by MikaelHolmstrom** [comment]
Thanks again, this has been fixed, and will be added in the next build in a day or two: 1.2.59

**Comment by MikaelHolmstrom** [comment]
v1.2.59 is ready for download,
