### ISSUE TITLE
Rename VI (to .vim) now allowed

### ISSUE THREAD

**Issue by tgutzler** [opengds/OpenGDS#69]
When I right click on test.vi and select GOOP / Rename Vi...
and enter "test.vim" as New name I'm not allowed to rename because the name hasn't changed.
I think .vi to .vim should be accepted as name change
![image](https://user-images.githubusercontent.com/14195272/117388198-a6b1ee80-af2d-11eb-8c47-d38cc2416f7d.png)

**Comment by MikaelHolmstrom** [comment]
Excellent idea,
I've started to support vim, if you use the latest version and add a method name with the extension .vim, the gui changes to show that it will create a vim and limits some selections.
I hope you you'll start using 2020 soon, all new features and efforts is going into that version.

**Comment by tgutzler** [comment]
We're onboard. Switched over to 2020 this week with the beta version of GDS.

**Comment by MikaelHolmstrom** [comment]
v1.2.59 is ready for download, check the singleton template VIs, and GetInstance changes a s well to see if you think this is okay for you?

**Comment by tgutzler** [comment]
Looking good.
Except, I just discovered that there is a preview when you click on the method template in the create method dialog. Unfortunately, the preview doesn't match the generated code (sometimes).
Preview:
![image](https://user-images.githubusercontent.com/14195272/117734662-3fe74a80-b237-11eb-9ac2-44f6c19a20a1.png)
Actual:
![image](https://user-images.githubusercontent.com/14195272/117734736-6c9b6200-b237-11eb-974b-5d33d583f135.png)

**Comment by MikaelHolmstrom** [comment]
I better fix that, thanks

**Comment by MikaelHolmstrom** [comment]
Fixed, 2 images have been updated in this folder:
resource\Framework\Providers\Open_GDS\ClassProviders\MethodImages
Which the ..\MethodTemplatesImages.ini  file is pointing to.
