### ISSUE TITLE
Stans Class 1_class included in release builds

### ISSUE THREAD

**Issue by JamesBalisciano** [opengds/OpenGDS#72]
Release 1.2.71 includes **Stans Class 1_class**.

Attempting to create a class from this template fails. This may have something to do with the missing parent class/interfaces that aren't found when I open the lvclass file, however I think the actual issue is that this template may have been unintentionally included in the distribution as I do not see it present in the repo.

![image](https://user-images.githubusercontent.com/38664065/148106183-db94fe96-2c6b-41d2-aac2-3e33c5fc4894.png)

**Comment by MikaelHolmstrom** [comment]
Thanks for letting me know, this should not be there :-).
It was "Stan" that had issues creating his own template and wanted me to make sure it worked.

**Comment by MikaelHolmstrom** [comment]
Done
