### ISSUE TITLE
OpenGDS 1.2.41 (LV2017) GOOP2 -> GOOP3 conversion fails due to incorrect path for the templates

### ISSUE THREAD

**Issue by koningsp** [opengds/OpenGDS#73]
The GOOP300_GetClassTemplatePath.vi still refers to the Symbio_GDS and not OpenGDS.
This will results in finding 'resource\Framework\Providers\Open_GDS\ClassProviders\Provider_EndevoGOOP300\Templates' and updating the files during conversion.

![image](https://user-images.githubusercontent.com/11059911/165258543-92458c31-f825-45d6-a347-957d438bf3a0.png)

**Comment by MikaelHolmstrom** [comment]
Fixed
