### ISSUE TITLE
OpenGDS 1.2.41 (LV2017) GOOP2 -> GOOP3 conversion sometimes deletes class VI's

### ISSUE THREAD

**Issue by koningsp** [opengds/OpenGDS#74]
The GOOP2 -> GOOP3 conversion sometimes deletes class VI's.
ConvertGoop2ToGoop3.vi -> State 'OpenClassesInMemory' a number of specific GOOP2 vi's are deleted.
From example the 'class version.vi' containing the 'Class Template Version'.
The following file 'class GetProtocolversion.vi' will also get deleted since it match 'Version.vi$'.

![image](https://user-images.githubusercontent.com/11059911/165260866-57b69a74-04b4-4d98-8efa-f75e52dfc29b.png)

**Comment by MikaelHolmstrom** [comment]
Do you have a GOOP2 class I can test with?
I've not used GOOP2 for the last 10 years :-)

**Comment by koningsp** [comment]
See attachment with a simple GOOP2 class. It has two methods that get deleted when I convert it to GOOP3 ('Goop2ToGoop3ConversionTest GetProtocolVersion.vi' and 'Goop2ToGoop3ConversionTest SetProtocolVersion.vi'

I used the old GOOP wizard default so it is an LLB.
![image](https://user-images.githubusercontent.com/11059911/166233499-2b6ded10-c07e-4ab0-8c41-9bbc05a2dcc7.png)

[Goop2ToGoop3ConversionTest.zip](https://github.com/opengds/OpenGDS/files/8602766/Goop2ToGoop3ConversionTest.zip)

**Comment by koningsp** [comment]
Possible fix: Use the 'ClassPrefix' to get the file correct files.
Need to update the Update '\2Evit$' to '.*\2Evit$' to find all VIT of the class

![image](https://user-images.githubusercontent.com/11059911/168978458-a904a84a-89b9-4423-8fb2-c97e75a175a2.png)

**Comment by MikaelHolmstrom** [comment]
Thanks for you feedback, this is now fixed in version 1.2.81.
You can find it in the beta testing listing soon.
