### ISSUE TITLE
Installing in LV 2022Q3 32-bit

### ISSUE THREAD

**Issue by jonasmaki** [opengds/OpenGDS#78]
The Beta testing for 2022 VI package cannot be opened and installed in 2022, error message saying:

"None of the packages found can be installed in your currently displayed LabVIEW version because they are not compatible."

**Comment by MikaelHolmstrom** [comment]
Okay, I'll fix that, but it will work if you run the stand-alone installation VI next to the package.

**Comment by jonasmaki** [comment]
Yes I've installed it that way. Just wanted to inform that the package was not working if you didn't know.

**Comment by jimkring** [comment]
Is this a VIPM bug? Or, is it a problem with the package metadata?--
Jim Sent from my mobile.

**Comment by MikaelHolmstrom** [comment]
The spec format is very old 2014.
I better update to 2017 format.
I'll let you verify the format for the next build

**Comment by JamesBalisciano** [comment]
> Is this a VIPM bug? Or, is it a problem with the package metadata?-- Jim Sent from my mobile.

It appears to be the metadata. I just ran into this and did a bit of testing after noting that the 1.2.86 VIP for 2020 worked properly.

The version requirement in the 2022 package is:

    Exclusive_LabVIEW_Version="=22.0"

For LabVIEW 2022 Q3 it should be:

    Exclusive_LabVIEW_Version="=22.3"

I made that edit and VIPM accepted the package and installed it properly.

**Comment by MikaelHolmstrom** [comment]
@jimkring , So all my OpenGDS builds are using the "Exclusive_LabVIEW_Version" in thew spec file.
I set it to =XX.0 and that have worked in the past, but now with the Q[1-4] version the version becomes XX.1-4.
So can I set the Exclusive_LabVIEW_Version to just XX instead of XX.0
E.g. 
Exclusive_LabVIEW_Version="=22"
if not I can change it to Exclusive_LabVIEW_Version=">=22.0"

**Comment by MikaelHolmstrom** [comment]
Thanks for reminding me. I just started a new build.
FYI We recently moved to LV2023Q3, and that has caused us so much build issues.
Currently we have to use LV2023Q1 to build many of our applications...so that is just a warning if you're moving to 2023Q3

**Comment by jonasmaki** [comment]
Good to know, thank you Mikael!

**Comment by Bas-vE** [comment]
I think this issue is resolved as the new packages have 
Exclusive_LabVIEW_Version=">=23.0"
