### ISSUE TITLE
YouTube Links on the Help Section is broken!

### ISSUE THREAD

**Issue by achuthaperumal** [opengds/OpenGDS#79]
Hi,
I'm interested in learning about GDS Toolkit. When I was surfing through the Help Section, Demo Video Links are broken meaning It says its a private video! Can you please make the videos public?

This Issue is observed in OpenGDS_1.2.86(LV2020)_LV2022-32

**Comment by MikaelHolmstrom** [comment]
Hi, Sorry yes NI have removed those links.
And the Help file definitely needs to be updated.
We have some help info here:
https://forums.ni.com/t5/GDS-Goop-Development-Suite/bd-p/5050
I did an hour presentation here:
https://www.youtube.com/watch?v=VWsOIsn8fSA
But that just goes through all the feature of the tool, not how e.g. the GOOP4 DVR template works and why it's deigned like it is.
You can view this as well: https://www.youtube.com/watch?v=nJDs4RpdkWA

**Comment by achuthaperumal** [comment]
Thanks, @MikaelHolmstrom  

> how e.g. the GOOP4 DVR template works and why it's deigned like it is.

Actually, I'd like to learn more about the design patterns... Any whitepaper or links available? If so kindly let me know...

**Comment by achuthaperumal** [comment]
Thanks! Eagerly waiting for them!!

**Comment by MikaelHolmstrom** [comment]
The design patterns will be posted here, just cleaning them up a bit:
https://github.com/opengds/DesignPatterns

**Comment by achuthaperumal** [comment]
@MikaelHolmstrom Thanks! I appreciate your effort in building this fantastic tool!

**Comment by MikaelHolmstrom** [comment]
Okay the first commit is not done here:
https://github.com/opengds/DesignPatterns.git
