### ISSUE TITLE
Creating an override method renames reference out

### ISSUE THREAD

**Issue by Bas-vE** [opengds/OpenGDS#82]
The reference out terminal gets renamed to "reference in" when creating an override method

![image](https://github.com/opengds/OpenGDS/assets/16207111/5df99c66-2e68-473b-ac50-352ca471c58e)

**Comment by MikaelHolmstrom** [comment]
Fixed in the next version, it was just the template files for 4 and 5 CP sized of Sub classes that had the wrong name

**Comment by MikaelHolmstrom** [comment]
v1.3.6 is ready for testing
