### ISSUE TITLE
Improve Destroy.vi speeds

### ISSUE THREAD

**Issue by Bas-vE** [opengds/OpenGDS#84]
A colleague of mine had the idea to remove the unbundle by name from the destroy.vi because after deleting the data value reference it will give you all the data in the data value reference. He also did a benchmark, which shows that for larger datasets in the attributes it takes half the time. We've also tested this with references of other classes in the attributes and this shows no problems.

![image](https://github.com/opengds/OpenGDS/assets/16207111/f7c21d1f-40fe-449e-a33f-403fa6b9eb41)

[TestDestroyPerformance.zip](https://github.com/opengds/OpenGDS/files/13441373/TestDestroyPerformance.zip)

**Comment by MikaelHolmstrom** [comment]
I do like this :-)

**Comment by MikaelHolmstrom** [comment]
Done, also fixed the Singleton templates
