### ISSUE TITLE
Build breaks after cloning class and not changing attributes

### ISSUE THREAD

**Issue by Bas-vE** [opengds/OpenGDS#87]
The issue, when cloning a class, the output DVR reference of the object attributes does not change to the new class. This has no influence when running your code in the Development environment, but when building LabVIEW cannot save the blockdiagram, and the error is not very easy to understand when you don't know where this is coming from.

As you can see in this image, we've create the class TestFirst.lvclass with a simple property method vi named GetAttribute1.vi and after that we cloned the class as TestSecond.lvclass. when you open the GetAttribute1.vi of the cloned class and put your mouse cursor over the dvr output of the get_attributes you can see in the context help that the data on this wire is still from the original class.
![image](https://github.com/opengds/OpenGDS/assets/16207111/08ffcfad-1cea-4595-8d62-f87576a66564)

To remedy this, we've altered the cloneclass.vi of the GDS by searching for the first cluster and dropping the string constant in that cluster. and we've added some applies to just to be sure. I've added a screenshot and the fixed vi, which is made in LV2020. The only thing I changed in this vi is the case you're seeing in the screenshot.

![image](https://github.com/opengds/OpenGDS/assets/16207111/72733e2a-10dc-467e-8678-9934dc0f62f5)
[CloneClass.zip](https://github.com/opengds/OpenGDS/files/14388136/CloneClass.zip)

**Comment by MikaelHolmstrom** [comment]
Done
