### ISSUE TITLE
Add must override flag

### ISSUE THREAD

**Issue by jashcroft123** [opengds/OpenGDS#89]
Similar to LabVIEW Native tool the VI name is appended with '*' if it is a must override method. I have done this on a local copy of the GOOP dev suite:
![image](https://github.com/opengds/OpenGDS/assets/54602676/36a5a311-d42e-4b03-a5be-42de23724d27)

**Comment by jashcroft123** [comment]
Just loading it up now, it's worth noting that I only slapped it together and tried to change as little as possible. I believe it should have a bug that if a method is must override but has already been implemented by a parent it will still show a *

**Comment by Bas-vE** [comment]
Added in the next version
