### ISSUE TITLE
Cloned VI with "&" in name creates clone with missing "&"

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#9]
@MikaelHolmstrom 
Steps to reproduce:

1. You have a VI named such as:  "words & text.VI"
2. Right-Click on the VI and select "Clone VI..".
3. After you clone the VI, you get: "words  text.VI"

**Comment by MikaelHolmstrom** [comment]
Okay, I'll let "&" be a valid character

**Comment by MikaelHolmstrom** [comment]
Done, I'm just removed these characters now: <>:"/\|?*
