### ISSUE TITLE
Always create 4x4x4 connector pane for property node methods

### ISSUE THREAD

**Issue by StefanCals** [opengds/OpenGDS#92]
Creating a new property node method, in a class that is made with the 5x6x5 or 6x8x6 Class Template, will create the wrong connector pane for the property node method. 
It creates the connector pane, depending on the Class Template Used (by creation of the class).
While it should create it 4x4x4 ALWAYS. 

In class with :
![image](https://github.com/opengds/OpenGDS/assets/36990897/cb6d0cd7-be60-41c4-949d-cd1e8a5d6119)

GOOP >> Add Method...
![image](https://github.com/opengds/OpenGDS/assets/36990897/f73010a1-372b-469c-9b92-0e77a047a8c1)

Creates : (is broken because of wrong connector pane)
![image](https://github.com/opengds/OpenGDS/assets/36990897/a3b4c388-d96f-4e0b-b285-a35cf1c49e85)

But should create : (has right connector pane)
![image](https://github.com/opengds/OpenGDS/assets/36990897/2b64ebb4-3baa-46c2-9951-6bf0086a615f)

Probably the property node template methods for the 5x6x5 and 6x8x6 Class Template are made with VIs with these connector panes. These should probably be changed to 4x4x4.

**Comment by StefanCals** [comment]
Issue can be fixed by editing the following files to a 4x4x4 connector pane : 

C:\Program Files (x86)\National Instruments\LabVIEW 2020\resource\Framework\Providers\Open_GDS\ClassProviders\Provider_EndevoGOOP400\Templates\\...

- G4BaseTemplate_Simple_5x6x5\methods\\...
  - G4BaseTemplate_Simple_5x6x5_ReadProperty.vi
  - G4BaseTemplate_Simple_5x6x5_WriteProperty.vi
- G4BaseTemplate_Simple_6x8x6\methods\\...
  - G4BaseTemplate_Simple_6x8x6_ReadProperty.vi
  - G4BaseTemplate_Simple_6x8x6_WriteProperty.vi

and

- G4SubTemplate_Simple_5x6x5\methods\\...
  - G4SubTemplate_Simple_5x6x5_ReadProperty.vi
  - G4SubTemplate_Simple_5x6x5_WriteProperty.vi
- G4SubTemplate_Simple_6x8x6\methods\\...
  - G4SubTemplate_Simple_6x8x6_ReadProperty.vi
  - G4SubTemplate_Simple_6x8x6_WriteProperty.vi

**Comment by MikaelHolmstrom** [comment]
Thanks I'll update these templates
