### ISSUE TITLE
Get Set Property Method doesn't consider  File naming option in Default Configurations Dialog: "File names with spaces.vi"

### ISSUE THREAD

**Issue by pettaa123** [opengds/OpenGDS#94]
I just downloaded and installed GOOP for 2023, great project!

![image](https://github.com/opengds/OpenGDS/assets/31046837/cc281a69-c740-4b9a-b690-4d356669255c)
When 
File naming option in Default Configurations Dialog is set to: "File names with spaces.vi"

The Get Set property suggests still camelback.

**Comment by pettaa123** [comment]
Can I adapt some template in order to have a space between "Get" and the property name by default?

**Comment by MikaelHolmstrom** [comment]
Added this :-)

**Comment by pettaa123** [comment]
File name with spaces doesn't suggest a space between Get and the Attribute. For a attribute named CFG Base it suggest: GetCFG Base instead of Get CFG Base

**Comment by MikaelHolmstrom** [comment]
Fixed
